---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "relayr-app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "relayr-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "relayr-app.name" . }}
    spec:
      initContainers:
      - name: check-db-ready
        image: mysql:latest
        command: ['sh', '-c',
          'until mysqladmin -s ping -h $DATABASE_HOST -u root -p${DATABASE_PASSWORD} -P ${DATABASE_PORT};
          do echo waiting for database; sleep 2; done;']
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ template "relayr-app.name" . }}-mysql"
              key: mysql-root-password
        - name: DATABASE_NAME
        {{- if .Values.database.name }}
          value: "{{ .Values.database.name }}"
        {{- else }}
          value: "{{ template "relayr-app.name" . }}"
        {{ end }}
        - name: DATABASE_PORT
        {{- if .Values.database.port }}
          value: "{{ .Values.database.port }}"
        {{- else }}
          value: "3306"
        {{ end }}
        - name: DATABASE_HOST
          value: "{{ template "relayr-app.name" . }}-mysql"
      containers:
      - name: {{ template "relayr-app.name" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: DATABASE_USER
        {{- if .Values.database.user }}
          value: "{{ .Values.database.user }}"
        {{- else }}
          value: "{{ template "relayr-app.name" . }}"
        {{ end }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ template "relayr-app.name" . }}-mysql"
              key: mysql-password
        - name: DATABASE_NAME
        {{- if .Values.database.name }}
          value: "{{ .Values.database.name }}"
        {{- else }}
          value: "{{ template "relayr-app.name" . }}"
        {{ end }}
        - name: DATABASE_PORT
        {{- if .Values.database.port }}
          value: "{{ .Values.database.port }}"
        {{- else }}
          value: "3306"
        {{ end }}
        - name: DATABASE_HOST
          value: "{{ template "relayr-app.name" . }}-mysql"
        ports:
        - name: http
          containerPort: {{ .Values.targetPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}