apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "relayr-app.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ template "relayr-app.name" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /.*
          backend:
            serviceName: {{ template "relayr-app.name" . }}
            servicePort: {{ .Values.service.port }}